### ISSUE TITLE
Ruby 2.3 specs

### ISSUE THREAD

**Issue by eregon** [ruby/spec#175]
We should aim to write specs for all new features, as usually the coverage is rather limited and it would greatly help other implementations to get the behavior right and faster.

From https://github.com/ruby/ruby/blob/v2_3_0/NEWS:
Only relevant items are kept for brevity.
### Language changes
- frozen-string-literal pragma:
  - [x] 8a769004ae039ac1d676d1f3a836e6d8179eeaad new pragma, frozen-string-literal has been experimentally introduced.
    [Feature #8976](https://bugs.ruby-lang.org/issues/8976)
  - [x] b9c349e0007a52b64f4d6da1004bf8270f99640f besides, --enable/--disable=frozen-string-literal options also have
    been introduced. [Feature #8976](https://bugs.ruby-lang.org/issues/8976)
  - [x] a0e55dbf8ce1ce2ffbc3ac16a208db2631e8dae0 command line options --debug or --debug=frozen-string-literal enable
    additional debugging mode which shows created location with at frozen
    object error (RuntimeError).
    [Feature #11725](https://bugs.ruby-lang.org/issues/11725)
- safe navigation operator:
  - [x] #274 new method call syntax, `object&.foo`, method #foo is called on
    `object` if it is not nil.
    this is similar to `try!` in Active Support, except:
    - method name is syntactically required
        `obj.try! {}` # valid
        `obj&. {}`    # syntax error
    - arguments are evaluated only if a call is made:
        `obj.try!(:foo, bar())  # bar() is always evaluated`
        `obj&.foo(bar())        # bar() is conditionally evaluated`
    - attribute assignment is valid
        `obj&.attr += 1`
      [Feature #11537](https://bugs.ruby-lang.org/issues/11537)
- the `did_you_mean` gem:
  - [x] #351 When a NameError or NoMethodError occurs because of a typo in the name,
    the did_you_mean gem automatically suggests other names similar to the
    method name.
    ```ruby
    "Yuki".starts_with?("Y")
    # => NoMethodError: undefined method `starts_with?' for "Yuki":String
    #    Did you mean?  start_with?
    ```
- indented here document:
  - [x] 57c69fcd946259588da3cc850daed035d8c0d77d #340 new string literal, here document starts with `<<~`.
    refer doc/syntax/literals.rdoc for more details.
    [Feature #9098](https://bugs.ruby-lang.org/issues/9098)
### Core classes updates (outstanding ones only)
- ARGF
  - [x] 09381495a5ac870cff71227ee31afaa448aa2260 ARGF.read_nonblock supports `exception: false` like IO#read_nonblock.
    [Feature #11358](https://bugs.ruby-lang.org/issues/11358)
- Array
  - [x] 0cf2e94df86a97e38708a4a2c7947cd71e71368a Array#bsearch_index [Feature #10730](https://bugs.ruby-lang.org/issues/10730)
  - [x] #161 #169 #170 #171 #172 Array#dig [Feature #11643](https://bugs.ruby-lang.org/issues/11643)
- Comparable
  - [x] f59a862dd9d6033a0579cc51c9afee29682fa340 Comparable#== no longer rescues exceptions [Feature #7688](https://bugs.ruby-lang.org/issues/7688)
- Enumerable
  - [x] 354365664d590579a607f7e63295c15654597278 Enumerable#grep_v is added as inverse version of Enumerable#grep.
    [Feature #11049](https://bugs.ruby-lang.org/issues/11049)
  - [x] #168 Enumerable#chunk_while [Feature #10769](https://bugs.ruby-lang.org/issues/10769)
- Enumerator::Lazy
  - [x] 59b20435671f9c3681ffea4888638ce3fc9851bb Enumerator::Lazy#grep_v [Feature #11773](https://bugs.ruby-lang.org/issues/11773)
- File
  - [x] 48060b6f969ab2782de76b4c98e92b59b945f40b File.mkfifo [Feature #11536](https://bugs.ruby-lang.org/issues/11536)
  - [x] #356 Add File::TMPFILE corresponding to O_TMPFILE
- Hash
  - [x] 66e5c086b39d5debd88301f8f44ebfea38ca0687 Hash#fetch_values [Feature #10017](https://bugs.ruby-lang.org/issues/10017)
  - [x] #161 Hash#dig [Feature #11643](https://bugs.ruby-lang.org/issues/11643)
  - [x] #160 Hash#<=, Hash#<, Hash#>=, Hash#> [Feature #10984](https://bugs.ruby-lang.org/issues/10984)
  - [x] #159 Hash#to_proc [Feature #11653](https://bugs.ruby-lang.org/issues/11653)
- IO
  - [x] #357 new mode flag File::SHARE_DELETE is available.
    this flag means to permit deleting opened file on Windows, but currently
    this affect only files opened as binary.  [Feature #11218](https://bugs.ruby-lang.org/issues/11218)
  - [x] 4cb076575a7f4a4c0f1aaaf3e8b0d41d4fda1910 new option parameter `flags` is added.
    this parameter is bitwise-ORed to oflags generated by normal mode argument.
    [Feature #11253](https://bugs.ruby-lang.org/issues/11253)
- Kernel
  - [x] ba17b3de1c1f579d53dfeb1a341260ebce54d89f Kernel#loop, when stopped by a StopIteration exception, returns
    what the enumerator has returned instead of nil. [Feature #11498](https://bugs.ruby-lang.org/issues/11498)
- Module
  - [x] 3e9505b9bf196106b37b9420a6a5c0370b630aa3 Module#deprecate_constant [Feature #11398](https://bugs.ruby-lang.org/issues/11398)
- NameError
  - [x] #177 #178 NameError#receiver is added to take the receiver object. [Feature #10881](https://bugs.ruby-lang.org/issues/10881)
- Numeric
  - [x] 6e164b07b511b2c2e5a8f5a3dd555044210fd62f 45c334ece2d13ebb3530a262c3445ea45c7a55eb Numeric#positive? and Numeric#negative? are added, which return
    true when the receiver is positive and negative respectively.
    [Feature #11151](https://bugs.ruby-lang.org/issues/11151)
- Queue (Thread::Queue)
  - [x] 5885e2b9af53f5c0047c8f6367ff6bf2468199a7 Queue#close is added to notice a termination. [Feature #10600](https://bugs.ruby-lang.org/issues/10600)
- String
  - [x] 9d7f0727ac5d225695da6b9dffac47bea9be4f15 0391aea1a55c7e88eea682cd9c103f7e93db0b9a String#+@ and String#-@ are added to get mutable/frozen strings.
    [Feature #11782](https://bugs.ruby-lang.org/issues/11782)
  - [x] 214cf9e77fce1bd178efeb3a22e6be1710477ed2 String.new now accepts new option parameter `encoding`.
    [Feature #11785](https://bugs.ruby-lang.org/issues/11785)
- Struct
  - [x] 065e422c18fe1dc65880f1ff9f9f4504852db45c Struct#dig [Feature #11688](https://bugs.ruby-lang.org/issues/11688)
- Thread
  - [x] #165 Thread#name, Thread#name= are added to handle thread names [Feature #11251](https://bugs.ruby-lang.org/issues/11251)
### Core classes compatibility issues (excluding feature bug fixes)
- Array
  - [x] #273 Array#select!, Array#keep_if, Array#reject!, and Array#delete_if
    no longer changes the receiver array instantly every time the
    block is called.  [Feature #10714](https://bugs.ruby-lang.org/issues/10714)
  - [x] #307 Array#flatten and Array#flatten! no longer try to call #to_ary
    method on elements beyond the given level.  [Bug #10748](https://bugs.ruby-lang.org/issues/10748)
  - [x] #307 Array#inspect doesn't raise error even if its content returns
    a string which is not compatible with Encoding.default_external
    as inspected result. [Feature #11801](https://bugs.ruby-lang.org/issues/11801)
- Enumerable
  - [x] 376c9eaa991630d551e92bcf6159b371b7641486 8b118fdc75d207c37c6b3000885beb802942bf44 Enumerable#chunk and Enumerable#slice_before no longer takes the
    initial_state argument.  [Feature #10958](https://bugs.ruby-lang.org/issues/10958)
    Use a local variable instead to maintain a state.
- File::Stat
  - [x] 67f285bdf53dc5bf5e0a2ecaa057eecd83c1e6d9 On Windows File::Stat#ino always returned 0, but now returns
    BY_HANDLE_FILE_INFORMATION.nFileIndexHigh/Low.  [Feature #11216](https://bugs.ruby-lang.org/issues/11216)
- Hash
  - [x] #307 Hash#inspect doesn't raise error even if its content returns
    a string which is not compatible with Encoding.default_external
    as inspected result. [Feature #11801](https://bugs.ruby-lang.org/issues/11801)
- IO
  - [x] adfd6bd005cd0f2c0abb0329f88ac4227304d5cc IO#close doesn't raise when the IO object is closed.  [Feature #10718](https://bugs.ruby-lang.org/issues/10718)
  - [x] 292f31fc21293c2a006c28790267a811affb01be IO#each_codepoint raises an exception at incomplete character
    before EOF when conversion takes place.  [Bug #11444](https://bugs.ruby-lang.org/issues/11444)
- Module
  - [x] e1ea96364cff9a889074673f3f76a37c983bc680 Module#define_method and Object.define_singleton_method now
    require method body, Proc, Method, or a block, and raise
    ArgumentError if no block is given directly.  [Bug #11283](https://bugs.ruby-lang.org/issues/11283)
- pack/unpack (Array/String)
  - [x] #331 j and J directives for pointer width integer type.  [Feature #11215](https://bugs.ruby-lang.org/issues/11215)
### Stdlib updates (not pure-Ruby changes as these just depend on existing features)
- OpenSSL
  - [x] (no specs) OpenSSL::SSL::SSLSocket#accept_nonblock and
    OpenSSL::SSL::SSLSocket#connect_nonblock supports `exception: false`.
- Socket
  - [x] 600d30538c955ac1b3627dde602613af4ec4a078 Socket#connect_nonblock, Socket#accept_nonblock,
    TCPServer#accept_nonblock, UNIXServer#accept_nonblock,
    BasicSocket#recv_nonblock, BasicSocket#recvmsg_nonblock,
    BasicSocket#sendmsg_nonblock all support `exception: false` to return
    :wait_readable or :wait_writable symbols instead of raising
    IO::WaitReadable or IO::WaitWritable exceptions
    [Feature #10532] [Feature #11229](https://bugs.ruby-lang.org/issues/11229)
  - [x] e000de6a10bf55c087936629a32ea2493fe6e885 BasicSocket#recv and BasicSocket#recv_nonblock allow an output
    String buffer argument like IO#read and IO#read_nonblock to reduce
    GC overhead [Feature #11242](https://bugs.ruby-lang.org/issues/11242)
- StringIO
  - [ ] In read-only mode, StringIO#set_encoding no longer sets the encoding
    of its buffer string.  Setting the encoding of the string directly
    without StringIO#set_encoding may cause unpredictable behavior now.
    [Bug #11827](https://bugs.ruby-lang.org/issues/11827)
### Stdlib compatibility issues (not pure-Ruby changes as these just depend on existing features)
- lib/base64.rb
  - [x] #315 Base64.urlsafe_encode64: added a "padding" option to suppress
    the padding character ("=").  [Feature #10740](https://bugs.ruby-lang.org/issues/10740)
  - [x] #315 Base64.urlsafe_decode64: now it accepts not only correctly-padded
    input but also unpadded input.  [Feature #10740](https://bugs.ruby-lang.org/issues/10740)
- ext/coverage/coverage.c
  - [x] #217 Coverage.peek_result: new method to allow coverage to be captured without
    stopping the coverage tool.  [Feature #10816](https://bugs.ruby-lang.org/issues/10816)
- Net::FTP
  - [x] 8126e53317d2c1b9ed06d65fc009aa3c8f3c32fe #158 Connections are in passive mode per default now.  The default mode can
    be changed by Net::FTP.default_passive=.  [Feature #11612](https://bugs.ruby-lang.org/issues/11612)
### C API updates
- [x] 1b4d6a222143dc3692f03a99f0af8c57c1135ff7 rb_define_class_id_under() now raises a TypeError exception when the
  class is already defined but its superclass does not match the given
  superclass, as well as definitions in ruby level.
- [x] ed926452f26ec50e4520ce3d0f14e86cc3cd7427 rb_timespec_now() is added to fetch current datetime as struct timespec.
  [Feature #11558](https://bugs.ruby-lang.org/issues/11558)
- [x] e976989234e2f11d3f4fba6cb0ad68eb01c3c763 rb_time_timespec_new() is added to create a time object with epoch,
  nanosecond, and UTC/localtime/time offset arguments.  [Feature #11558](https://bugs.ruby-lang.org/issues/11558)

**Comment by eregon** [comment]
About Hacktoberfest: any PR with specs covering one of those points would greatly help Ruby implementations and help to specify Ruby's 2.3 behavior!
There are plenty of existing specs to take inspiration from.
Find me on `#rubyspec` on Freenode or just create an issue to discuss.

**Comment by iliabylich** [comment]
@eregon Working on adding specs for "squiggly heredoc" from https://github.com/opal/opal/pull/1397. I guess all specs must be wrapped with `eval`, right? Is it possible to exclude the whole file from the test suite by specifying required ruby version? I just feel that wrapping all those heredocs with `eval` may look scary.

Or can we extract all examples to a separate file and required it in a context of `ruby_version_is "2.3"`?
In https://github.com/ruby/spec/pull/318 `require` happens directly in the test. Does moving to an outer context break anything?

**Comment by eregon** [comment]
@iliabylich Thanks!
Fixtures files is the best for this.
> Or can we extract all examples to a separate file and required it in a context of ruby_version_is "2.3"?

Yes, it's OK to require within the version guard, I moved it since it was used in a single spec.

**Comment by eregon** [comment]
All new features of 2.3 are now finally properly specified in ruby/spec!

We need a better way to deal with this, it's too time consuming.
Ideally, people implementing the features would also contribute a spec.
MRI tests are often not optimal due to testing many different aspects together, making it very likely to fail for reasons unrelated to the new feature on alternative Ruby implementations.

**Comment by eregon** [comment]
I would like to thank @headius, @mjago, @sgarciac and @iliabylich for the big help on these specs! :tada: 
We would not make it without you!
