### ISSUE TITLE
Write specs for new Ruby 2.4 features and changes

### ISSUE THREAD

**Issue by eregon** [ruby/spec#473]
ruby/spec already contains some specs for 2.4, but we should aim to cover all new features and important changes.
This will improve the test coverage of these features, allow other Ruby implementations to implement these faster with more confidence and document clearly the new behavior.

The new specs should be within a version guard block:
```ruby
ruby_version_is "2.4" do
  # New specs
end
```

From https://github.com/ruby/ruby/blob/ruby_2_4/NEWS:
Only relevant items are kept for brevity.

# NEWS for Ruby 2.4

This document is a list of user visible feature changes made between releases except for bug fixes.

### Language changes

- [x] #504 Multiple assignment in conditional expression is now allowed.  [Feature #10617](https://bugs.ruby-lang.org/issues/10617)

- [x] #509 Rescue modifier now applicable to method arguments.  [Feature #12686](https://bugs.ruby-lang.org/issues/12686)

- [x] #530 Toplevel return is now allowed.  [Feature #4840](https://bugs.ruby-lang.org/issues/4840)

### Core classes updates (outstanding ones only)

* Array

  - [x] #375 Array#concat [Feature #12333](https://bugs.ruby-lang.org/issues/12333)
    Now takes multiple arguments.

  - [x] f07c3de42de7ccaf021cff62af520d11db62966e 630ed7f2bfcd68ccd8d53651fb8344fd90c4a510 Array#max and Array#min.  [Feature #12172](https://bugs.ruby-lang.org/issues/12172)
    This may cause a tiny incompatibility: if you redefine
    Enumerable#max and call max to an Array, your redefinition will be
    now ignored.  You should also redefine Array#max.

  - [x] #495 Array#pack [Feature #12754](https://bugs.ruby-lang.org/issues/12754)
    Now takes optional argument `buffer:' to reuse already allocated buffer.

  - [x] #492 Array#sum (can share with 7f2961d95aeb06719bd80399092e15af37a853d4) [Feature #12217](https://bugs.ruby-lang.org/issues/12217)
    This is different from Enumerable#sum in that Array#sum doesn't depend on
    the definition of each method.

* Comparable

  - [x] 6baf83f4b00fcbbabcc87405889d352f5651eb6f Comparable#clamp.  [Feature #10594](https://bugs.ruby-lang.org/issues/10594)

* Dir

  - [x] #481 #482 Dir.empty?.  [Feature #10121](https://bugs.ruby-lang.org/issues/10121)

* Enumerable

  - [x] e00328a1fefd56dcc82421e689d971de3926f7bd Enumerable#chunk called without a block now return an Enumerator    [Feature #2172](https://bugs.ruby-lang.org/issues/2172)
  - [x] #446 Enumerable#sum  [Feature #12217](https://bugs.ruby-lang.org/issues/12217)
  - [x] #447 Enumerable#uniq  [Feature #11090](https://bugs.ruby-lang.org/issues/11090)

* Enumerator::Lazy

  - [x] #506 Enumerator::Lazy#chunk_while  [GH-1186](https://github.com/ruby/ruby/pull/1186)
  - [x] #448 Enumerator::Lazy#uniq  [Feature #11090](https://bugs.ruby-lang.org/issues/11090)

* File

  - [x] #476 File.empty?.  [Feature #9969](https://bugs.ruby-lang.org/issues/9969)

* Float

  - [x] #475  Float#ceil, Float#floor, and Float#truncate now take an optional
    digits, as well as Float#round.  [Feature #12245](https://bugs.ruby-lang.org/issues/12245)

  - [x] #477 Float#round now takes an optional keyword argument, half option, and
    the default behavior is round-up.  [Bug #12548](https://bugs.ruby-lang.org/issues/12548) [Bug #12958](https://bugs.ruby-lang.org/issues/12958)
    half option can be one of :even, :up, and :down.  [Feature #12953](https://bugs.ruby-lang.org/issues/12953)

* Hash

  - [x] #376 Hash#compact and Hash#compact!  [Feature #11818](https://bugs.ruby-lang.org/issues/11818)
  - [x] #377 Hash#transform_values and Hash#transform_values!  [Feature #12512](https://bugs.ruby-lang.org/issues/12512)

* Integer

  - [x] #483 Integer#ceil, Integer#floor, and Integer#truncate now take an optional
    digits, as well as Integer#round.  [Feature #12245](https://bugs.ruby-lang.org/issues/12245)

  - [x] #485 Integer#digits for extracting columns of place-value notation [Feature #12447](https://bugs.ruby-lang.org/issues/12447)

  - [x] #478 Integer#round now takes an optional keyword argument, half option, and the
    default behavior is round-up now.  [Bug #12548](https://bugs.ruby-lang.org/issues/12548) [Bug #12958](https://bugs.ruby-lang.org/issues/12958)
    half option can be one of :even, :up, and :down.  [Feature #12953](https://bugs.ruby-lang.org/issues/12953)

* IO

  - [x] #503 IO#gets, IO#readline, IO#each_line, IO#readlines, IO.foreach now takes
    an optional keyword argument, chomp flag.  [Feature #12553](https://bugs.ruby-lang.org/issues/12553)

* Kernel

  - [x] #451 Kernel#clone now takes an optional keyword argument, freeze flag.  [Feature #12300](https://bugs.ruby-lang.org/issues/12300)

* MatchData

  - [x] #449 MatchData#named_captures [Feature #11999](https://bugs.ruby-lang.org/issues/11999)
  - [x] #450 MatchData#values_at supports named captures [Feature #9179](https://bugs.ruby-lang.org/issues/9179)

* Module

  - Module#refine accepts a module as the argument now. [Feature #12534](https://bugs.ruby-lang.org/issues/12534)
  - Module.used_modules [Feature #7418](https://bugs.ruby-lang.org/issues/7418)

* Numeric

  - [x] #487 Numeric#finite?, Numeric#infinite? [Feature #12039](https://bugs.ruby-lang.org/issues/12039)

* Process

  - [x] Support CLOCK_MONOTONIC_RAW_APPROX, CLOCK_UPTIME_RAW, and
    CLOCK_UPTIME_RAW_APPROX which are introduced by macOS 10.12.

* Rational

  - [x] #493 Rational#round now takes an optional keyword argument, half option, and
    the default behavior is round-up now.  [Bug #12548](https://bugs.ruby-lang.org/issues/12548) [Bug #12958](https://bugs.ruby-lang.org/issues/12958)
    half option can be one of :even, :up, and :down.  [Feature #12953](https://bugs.ruby-lang.org/issues/12953)

* Regexp

  - [x] #511 meta character \X matches Unicode 9.0 characters with some workarounds
    for UTR #51 Unicode Emoji, Version 4.0 emoji zwj sequences.

  - [x] #379 Regexp#match? [Feature #8110](https://bugs.ruby-lang.org/issues/8110)
    This returns bool and doesn't save backref.

  * Update Onigmo 6.1.1.
    - [x] #532 Support absent operator https://github.com/k-takata/Onigmo/issues/82

* Regexp/String:
  - [x] Updated Unicode version from 8.0.0 to 9.0.0 [Feature #12513](https://bugs.ruby-lang.org/issues/12513)

* String

  - [x] #474 String#casecmp? [Feature #12786](https://bugs.ruby-lang.org/issues/12786)

  - [x] #375 String#concat, String#prepend [Feature #12333](https://bugs.ruby-lang.org/issues/12333)
    Now takes multiple arguments.

  - [x] #498 String#each_line, String#lines now takes an optional keyword argument,
    chomp flag.  [Feature #12553](https://bugs.ruby-lang.org/issues/12553)

  - [x] #379 String#match? [Feature #12898](https://bugs.ruby-lang.org/issues/12898)

  - [x] #488 String#unpack1 [Feature #12752](https://bugs.ruby-lang.org/issues/12752)

  - [x] #501 9c24b006b5e21d2596933f3878c8e2baee72c774 String#upcase, String#downcase, String#capitalize, String#swapcase and
    their bang variants work for all of Unicode, and are no longer limited
    to ASCII. Supported encodings are UTF-8, UTF-16BE/LE, UTF-32BE/LE, and
    ISO-8859-1~16. Variations are available with options. See the documentation
    of String#downcase for details. [Feature #10085](https://bugs.ruby-lang.org/issues/10085)

  - [x] #499 String.new(capacity: size) [Feature #12024](https://bugs.ruby-lang.org/issues/12024)

* StringIO

  - [x] #505 StringIO#gets, StringIO#readline, StringIO#each_line, StringIO#readlines now takes
    an optional keyword argument, chomp flag.  [Feature #12553](https://bugs.ruby-lang.org/issues/12553)

* Symbol

  - [x] #480 Symbol#casecmp? [Feature #12786](https://bugs.ruby-lang.org/issues/12786)

  - [x] 51d46b1c8b672fd679287bb3964295b3a64cc7aa 7604cbcd03c6c5bde3e8f6b11351f05f52d628d0 Symbol#match now returns MatchData.  [Bug #11991](https://bugs.ruby-lang.org/issues/11991)
repo
  - [x] #379 Symbol#match? [Feature #12898](https://bugs.ruby-lang.org/issues/12898)

  - [x] #502 Symbol#upcase, Symbol#downcase, Symbol#capitalize, and Symbol#swapcase now
    work for all of Unicode. See the documentation of String#downcase
    for details. [Feature #10085](https://bugs.ruby-lang.org/issues/10085)

* Thread

  - [x] #517 Thread#report_on_exception and Thread.report_on_exception    [Feature #6647](https://bugs.ruby-lang.org/issues/6647)

* TracePoint

  - [x] #508 TracePoint#callee_id [Feature #12747](https://bugs.ruby-lang.org/issues/12747)

* Warning

  - [x] #512 New module named Warning is introduced.  By default it has only
    one singleton method, named warn.  This makes it possible for
    3rd-party libraries to control the way warnings are handled.    [Feature #12299](https://bugs.ruby-lang.org/issues/12299)

### Stdlib updates (outstanding ones only)

* CGI

  - [x] #486 Don't allow , as a separator [Bug #12791](https://bugs.ruby-lang.org/issues/12791)

* CSV

  - [x] #524 Add a liberal_parsing option. [Feature #11839](https://bugs.ruby-lang.org/issues/11839)

* IPAddr

  - [x] #519 IPAddr#== and IPAddr#<=> no longer raise an exception if coercion fails.    [Bug #12799](https://bugs.ruby-lang.org/issues/12799)

* IRB

  - [x] Binding#irb: Start a REPL session like `binding.pry` at https://github.com/ruby/ruby/commit/493e48897421d176a8faf0f0820323d79ecdf94a.

* Logger

  - [x] #527 Allow specifying logger parameters in constructor such
    as level, progname, datetime_format, formatter. [Feature #12224](https://bugs.ruby-lang.org/issues/12224)
  - [x] #528 Add shift_period_suffix option. [Feature #10772](https://bugs.ruby-lang.org/issues/10772)

* Net::HTTP

  - [x] #520 New method: Net::HTTP.post [Feature #12375](https://bugs.ruby-lang.org/issues/12375)

* Net::FTP

  - [x] #540 Support hash style options for Net::FTP.new.
  - [x] #479 Add a new optional argument pathname to Net::FTP#status.
    Contributed by soleboxy. [GH-1478](https://github.com/ruby/ruby/pull/1478) [Feature #12965](https://bugs.ruby-lang.org/issues/12965)

* optparse

  - [x] #523 Add an into option. [Feature #11191](https://bugs.ruby-lang.org/issues/11191)

* pathname

  - [x] #484 New method: Pathname#empty? [Feature #12596](https://bugs.ruby-lang.org/issues/12596)

* REXML

  - [x] #531 REXML::Element#[]: If String or Symbol is specified, attribute
    value is returned. Otherwise, Nth child is returned. This is
    backward compatible change.

* set

  - [x] #507 #510 New methods: Set#compare_by_identity and Set#compare_by_identity?.    [Feature #12210](https://bugs.ruby-lang.org/issues/12210)

### Compatibility issues (excluding feature bug fixes)

- [x] #497 (need to add some specs to check Fixnum==Integer==Bignum and the #class of some values) Fixnum and Bignum are unified into Integer  [Feature #12005](https://bugs.ruby-lang.org/issues/12005)
  Fixnum class and Bignum class is removed.
  Integer class is changed from abstract class to concrete class.
  For example, 0 is an instance of Integer: 0.class returns Integer.
  The constants Fixnum and Bignum is bound to Integer.
  So obj.kind_of?(Fixnum) works as obj.kind_of?(Integer).
  At C-level, Fixnum object and Bignum object should be distinguished by
  FIXNUM_P(obj) and RB_TYPE_P(obj, T_BIGNUM).
  RUBY_INTEGER_UNIFICATION can be used to detect this feature at C-level.
  0.class == Integer can be used to detect this feature at Ruby-level.
  The C-level constants, rb_cFixnum and rb_cBignum, are removed.
  They can cause compilation failure.

- [x] 9c24b006b5e21d2596933f3878c8e2baee72c774 String/Symbol#upcase/downcase/swapcase/capitalize(!) now work for all of
  Unicode, not only for ASCII. [Feature #10085](https://bugs.ruby-lang.org/issues/10085)
  No change is needed if the data is in ASCII anyway or if the limitation
  to ASCII was only tolerated while waiting for a more extensive implementation.
  A change (using the :ascii option) is needed in cases where Unicode data
  is processed, but the operation has to be limited to ASCII only.
  A good example of this are internationalized domain names.

- [x] bd885a6c02ccef31d2b49361e049c724cacfa024 TRUE / FALSE / NIL
  These constants are now obsoleted. [Feature #12574](https://bugs.ruby-lang.org/issues/12574)
  Use true / false / nil resp. instead.

### Stdlib compatibility issues (excluding feature bug fixes)

* DateTime

  - [x] #490 DateTime#to_time now preserves timezone.  [Bug #12189](https://bugs.ruby-lang.org/issues/12189)

* shellwords

  - [x] #525 Shellwords.shellwords (shellsplit) treats the backslash as escape
    character only when followed by one of the following characters:
    $ ` " \ <newline>    [Bug #10055](https://bugs.ruby-lang.org/issues/10055)

* Time

  - [x] #490 Time#to_time now preserves timezone.  [Bug #12271](https://bugs.ruby-lang.org/issues/12271)

* Zlib

  - [x] Zlib.gzip and Zlib.gunzip [Feature #13020](https://bugs.ruby-lang.org/issues/13020)

### C API updates

- [x] rb_gc_adjust_memory_usage() [Feature #12690](https://bugs.ruby-lang.org/issues/12690)

### Implementation improvements

- Thread deadlock detection now shows their backtrace and dependency. [Feature #8214](https://bugs.ruby-lang.org/issues/8214)

### Not in the NEWS file

- [x] #472 38a6a1e4967c1873cb66aee65c87fcb9d758da04 `true`, `false`, `nil`, `Integer`, `Symbol`, etc no longer raise `TypeError` for `dup` and `clone`, but return `self`. [Feature #12979](https://bugs.ruby-lang.org/issues/12979)

**Comment by eregon** [comment]
Special thanks to @kachick and @nobu which already wrote a good part of these specs!
Let's make progress on the remaining ones!

**Comment by eregon** [comment]
If you want to help by contributing a spec for 2.4, please do so!
Choose a task and don't hesitate to ask help, by opening a Pull Request or an Issue.
All the existing files are examples of how to write a spec.

**Comment by boddhisattva** [comment]
@eregon Thanks for sharing the list of things one could work on. Really nice idea!:) You may want to just consider thinking about a way through which no two or more people are working on the same set of specs based on the above list.

For the record, I'm currently working on the Integer specs for `ceil, floor, truncate and round` as part of [this PR](https://github.com/ruby/spec/pull/483)

**Comment by eregon** [comment]
@boddhisattva You are right.
I suggest people announce here what they plan to work on, since there is some time before deciding to work on a spec and opening a PR.
(As we see, we already got two PRs for Dir.empty?)

**Comment by cadwallion** [comment]
I am about to start in on specs for Integer#digits.

**Comment by nilsding** [comment]
I'll tackle the `CGI::Cookie.parse` , separator one.

**Comment by cadwallion** [comment]
I'm about to start `Numeric#finite?` and `Numeric#infinite?`

**Comment by marcandre** [comment]
FYI, I added specs for `Enumerable#uniq`, since there were no tests for `uniq` without a block nor of how the elements are compared. 0a2d3158f0b10846d88a10cad6ffde6a69bcc9f4

**Comment by andrykonchin** [comment]
working on Array#sum

**Comment by andrykonchin** [comment]
working on Array#sum

**Comment by tegon** [comment]
I'm going to work on `Rational#round`

**Comment by kaid7** [comment]
I'm going to work on 
`Symbol#upcase, Symbol#downcase, Symbol#capitalize, and Symbol#swapcase now
work for all of Unicode. See the documentation of String#downcase
for details. Feature #10085`

**Comment by charle692** [comment]
I'm going to work on
`IO#gets, IO#readline, IO#each_line, IO#readlines, IO.foreach now takes
an optional keyword argument, chomp flag. Feature #12553`

**Comment by charle692** [comment]
I'm now going to start working on
`StringIO#gets, StringIO#readline, StringIO#each_line, StringIO#readlines now takes
an optional keyword argument, chomp flag. Feature #12553`

**Comment by jamesmacwilliam** [comment]
I'm working on `Language: Multiple assignment in conditional expression is now allowed. Feature #10617`

**Comment by joshgelbard** [comment]
Started working on `Enumerator::Lazy#chunk_while`.

It seems `#chunk`, `#slice_after`, `#slice_before`, and `#slice_when` are also missing, so I'll do those too. (Already did `#chunk`.)

**Comment by andrykonchin** [comment]
working on "New methods: Set#compare_by_identity and Set#compare_by_identity?"

**Comment by andrykonchin** [comment]
working on TracePoint#callee_id

**Comment by nilsding** [comment]
I'll start working on the `\X` operator in Regexp.

**Comment by nicoolas25** [comment]
Hello, I'll start working on this one:

> Rescue modifier now applicable to method arguments.

**Comment by nicoolas25** [comment]
Hi again, I'll work on this one now:

> New methods: Set#compare_by_identity and Set#compare_by_identity?.

**Comment by eregon** [comment]
I'll work on Thread#report_on_exception and Thread.report_on_exception.
Maybe we can even enable it by default in ruby/spec to catch threading errors more easily.

**Comment by andrykonchin** [comment]
working on "IPAddr#== and IPAddr#<=> no longer raise an exception if coercion fails."

**Comment by andrykonchin** [comment]
working on "New method: Net::HTTP.post"

**Comment by andrykonchin** [comment]
working on optparse into argument

**Comment by andrykonchin** [comment]
working on "CSV Add a liberal_parsing option. "

**Comment by aarek** [comment]
working on 

> Allow specifying logger parameters in constructor such
as level, progname, datetime_format, formatter.

**Comment by wswidzinski** [comment]
working on
> LOGGER: Add shift_period_suffix option.

**Comment by sgarciac** [comment]
FInished working on  : 

> Support absent operator k-takata/Onigmo#82

 #532 

> REXML::Element#[]: If String or Symbol is specified, attribute
> value is returned. Otherwise, Nth child is returned. This is
> backward compatible change.

 #531

**Comment by AndrewSpeed** [comment]
I'll work on:
> Support hash style options for Net::FTP.new.

From a quick glance, it looks like we don't have any specs for `Net::FTP.new`, so I'll add them as well

**Comment by submitnine** [comment]
Hi, I created a PR #619  to have some tests about "Regexp/String: Updated Unicode version from 8.0.0 to 9.0.0 Feature #12513".

**Comment by eregon** [comment]
I wrote specs for the last remaining items.
