### ISSUE TITLE
Write specs for new Ruby 2.5 features and changes

### ISSUE THREAD

**Issue by eregon** [ruby/spec#565]
ruby/spec already contains many specs for 2.5, but we should aim to cover all new features and important changes.
This will improve the test coverage of these features (and maybe discover a few bugs along the way), allow other Ruby implementations to implement the changes faster with more confidence and document clearly the new behavior.

The new specs should be within a version guard block:
```ruby
ruby_version_is "2.5" do
  # New specs
end
```

From https://github.com/ruby/ruby/blob/trunk/NEWS.
Only relevant items are kept for brevity.

### Language changes

- [x] rescue/else/ensure are allowed inside do/end blocks.  [Feature #12906](https://bugs.ruby-lang.org/issues/12906)
- [x] Top-level constant look-up is removed.  [Feature #11547](https://bugs.ruby-lang.org/issues/11547)

- [x] refinements take place in string interpolations.  [Feature #13812](https://bugs.ruby-lang.org/issues/13812)

### Core classes updates (outstanding ones only)

Array

- [x] Array#append  [Feature #12746](https://bugs.ruby-lang.org/issues/12746)
- [x] Array#prepend  [Feature #12746](https://bugs.ruby-lang.org/issues/12746)

Data

- [x] Is deprecated. It was a base class for C extensions, and it's not
  necessary to expose in Ruby level. [Feature #3072](https://bugs.ruby-lang.org/issues/3072)

Exception

- [x] Exception#full_message to retrieve a String expression of an exception,
  formatted in the same way in which Ruby prints out an uncaught exception.
  [Feature #14141](https://bugs.ruby-lang.org/issues/14141) [experimental]

Dir

- [x] Dir.glob provides new optional keyword argument, :base. [Feature #13056](https://bugs.ruby-lang.org/issues/13056)
- [x] Dir.children  [Feature #11302](https://bugs.ruby-lang.org/issues/11302)
- [x] Dir.each_child  [Feature #11302](https://bugs.ruby-lang.org/issues/11302)

Enumerable

- [x] Enumerable#{any?,all?,none?,one?} accept a pattern argument [Feature #11286](https://bugs.ruby-lang.org/issues/11286)

File

- [x] File.open accepts :newline option to imply text mode.  [Bug #13350](https://bugs.ruby-lang.org/issues/13350)
- [x] File#path raises an IOError for files opened with
  File::Constants::TMPFILE option. [Feature #13568](https://bugs.ruby-lang.org/issues/13568)
- [x] File::Stat#{atime,mtime,ctime} support fractional second timestamps on
  Windows 8 and later  [Feature #13726](https://bugs.ruby-lang.org/issues/13726)
- [x] File::Stat#ino and File.indentical? support ReFS 128bit ino on Windows 8.1
  and later  [Feature #13731](https://bugs.ruby-lang.org/issues/13731)
- [x] File.lutime  [Feature #4052](https://bugs.ruby-lang.org/issues/4052)

Hash

- [x] Hash#transform_keys  [Feature #13583](https://bugs.ruby-lang.org/issues/13583)
- [x] Hash#transform_keys!  [Feature #13583](https://bugs.ruby-lang.org/issues/13583)
- [x] Hash#slice  [Feature #8499](https://bugs.ruby-lang.org/issues/8499)

IO

- [x] IO#pread  [Feature #4532](https://bugs.ruby-lang.org/issues/4532)
- [x] IO#pwrite  [Feature #4532](https://bugs.ruby-lang.org/issues/4532)
- [x] IO#copy_stream tries copy offload with copy_file_range(2) [Feature #13867](https://bugs.ruby-lang.org/issues/13867)
- [x] IO#write accepts multiple arguments  [Feature #9323](https://bugs.ruby-lang.org/issues/9323)

IOError

- [x] IO#close might raise an error with message "stream closed",
  but it is refined to "stream closed in another thread". The new message
  is more clear for user.
  [Bug #13405](https://bugs.ruby-lang.org/issues/13405)

Integer

- [x] Integer#step no longer hides errors from coerce method when
  given a step value which cannot be compared with #> to 0.
  [Feature #7688](https://bugs.ruby-lang.org/issues/7688)
- [x] Integer#{round,floor,ceil,truncate} always return an Integer.
  [Bug #13420](https://bugs.ruby-lang.org/issues/13420)
- [x] #573 Integer#pow accepts modulo argument for calculating modular
  exponentiation.  [Feature #12508](https://bugs.ruby-lang.org/issues/12508) [Feature #11003](https://bugs.ruby-lang.org/issues/11003)
- [x] Integer#allbits?, Integer#anybits?, Integer#nobits? [Feature #12753](https://bugs.ruby-lang.org/issues/12753)
- [x] Integer.sqrt  [Feature #13219](https://bugs.ruby-lang.org/issues/13219)

Kernel

- [x] Kernel#yield_self   [Feature #6721](https://bugs.ruby-lang.org/issues/6721)
- [x] Kernel#pp  [Feature #14123](https://bugs.ruby-lang.org/issues/14123)
- [x] Kernel#warn(..., uplevel:n)  [Feature #12882](https://bugs.ruby-lang.org/issues/12882)

Method

- [x] Method#=== that invokes Method#call, as same as Proc#=== [Feature #14142](https://bugs.ruby-lang.org/issues/14142)

Module

- [x] Module#{attr,attr_accessor,attr_reader,attr_writer} become public [Feature #14132](https://bugs.ruby-lang.org/issues/14132)
- [x] Module#{define_method,alias_method,undef_method,remove_method} become public [Feature #14133](https://bugs.ruby-lang.org/issues/14133)

Numeric

- [x] Numerical comparison operators (<,<=,>=,>) no longer hide exceptions
  from #coerce method internally. Return nil in #coerce if the coercion is
  impossible.  [Feature #7688](https://bugs.ruby-lang.org/issues/7688)

Process

- [x] Precision of Process.times is improved if getrusage(2) exists. [Feature #11952](https://bugs.ruby-lang.org/issues/11952)
- [x] Process.last_status as an alias of $? [Feature #14043](https://bugs.ruby-lang.org/issues/14043)

Range

- [x] Range#initialize no longer hides exceptions when comparing begin and
  end with #<=> and raise a "bad value for range" ArgumentError
  but instead lets the exception from the #<=> call go through.
  [Feature #7688](https://bugs.ruby-lang.org/issues/7688)

Regexp

- [x] Support absent operator https://github.com/k-takata/Onigmo/issues/82
- [x] Support new 5 emoji-related Unicode character properties

String

- [x] #586 String#-@ deduplicates unfrozen strings.  Already-frozen
  strings remain unchanged for compatibility.  [Feature #13077](https://bugs.ruby-lang.org/issues/13077)
- [x] -"literal" (String#-@) optimized to return the same object
  (same as "literal".freeze in Ruby 2.1+) [Feature #13295](https://bugs.ruby-lang.org/issues/13295)
- [x] String#{casecmp,casecmp?} return nil for non-string arguments
  instead of raising a TypeError. [Bug #13312](https://bugs.ruby-lang.org/issues/13312)
- [x] #551 String#start_with? accepts a regexp [Feature #13712](https://bugs.ruby-lang.org/issues/13712)
- [x] String#delete_prefix, String#delete_prefix! [Feature #12694](https://bugs.ruby-lang.org/issues/12694)
- [x] String#delete_suffix, String#delete_suffix! [Feature #13665](https://bugs.ruby-lang.org/issues/13665)
- [x] String#each_grapheme_cluster and String#grapheme_clusters to
  enumerate grapheme clusters [Feature #13780](https://bugs.ruby-lang.org/issues/13780)
- [x] String#undump to unescape String#dump'ed string [Feature #12275](https://bugs.ruby-lang.org/issues/12275)

Struct

- [x] Struct.new takes `keyword_init: true` option to initialize members
  with keyword arguments. [Feature #11925](https://bugs.ruby-lang.org/issues/11925)

- [x] Regexp/String: Update Unicode version from 9.0.0 to 10.0.0 [Feature #13685](https://bugs.ruby-lang.org/issues/13685)

Thread

- [x] Thread#fetch  [Feature #13009](https://bugs.ruby-lang.org/issues/13009)
- [x] The default of Thread.report_on_exception is now true,
  showing unhandled exceptions terminating threads on $stderr.
  [Feature #14143](https://bugs.ruby-lang.org/issues/14143)

Time

- [x] Time#at receives 3rd argument which specifies the unit of 2nd argument.
  [Feature #13919](https://bugs.ruby-lang.org/issues/13919)

KeyError

- [x] #574 KeyError#receiver [Feature #12063](https://bugs.ruby-lang.org/issues/12063)
- [x] #574 KeyError#key      [Feature #12063](https://bugs.ruby-lang.org/issues/12063)

FrozenError

- [x] #568 New exception class. [Feature #13224](https://bugs.ruby-lang.org/issues/13224)

### Stdlib updates

Only stdlib which do not have tests are listed.
Many stdlib live in their own projects with their own tests.

RbConfig

- [x] RbConfig::LIMITS is added to provide the limits of C types.
  This is available when rbconfig/sizeof is loaded.

### Compatibility issues (excluding feature bug fixes)

Socket

- [x] BasicSocket#read_nonblock and BasicSocket#write_nonblock no
  longer set the O_NONBLOCK file description flag as side effect
  (on Linux only) [Feature #13362](https://bugs.ruby-lang.org/issues/13362)

Random

- [x] Random.raw_seed renamed to become Random.urandom.  It is now
  applicable to non-seeding purposes due to [Bug #9569](https://bugs.ruby-lang.org/issues/9569).

### Stdlib compatibility issues (excluding feature bug fixes)

mathn.rb

- [x] 49cdeadf451a54151d25ad5db11b234d87accf90 82145c5b8430e3a1b57b05ec3334e9b4c4f1106d Removed from stdlib. [Feature #10169](https://bugs.ruby-lang.org/issues/10169)

**Comment by eregon** [comment]
@marcandre @andrykonchin Could you tick the checkboxes of features you added specs for?
Unfortunately clicking on the checkbox is not enough, you need to edit the issue and add `x` inside the `[ ]`.
Please also do the same when adding new specs, first tick it to avoid conflicts :)

For contributors without commit access, please write here the when you start working on a spec, to avoid having multiple people working on the same specs.

**Comment by cadwallion** [comment]
Just a heads-up, but it appears you [fixed Integer#floor/truncate/ceil/round](https://github.com/ruby/spec/commit/64c06f9c9faccba0c461fd15eccaaa2df04dacfc) in October, but it hasn't been checked off yet. :)

**Comment by eregon** [comment]
@cadwallion Thanks, I checked it now :)

**Comment by cadwallion** [comment]
Working on FrozenError, PR should be up shortly.

**Comment by eregon** [comment]
For ruby/spec committers: I made the checkboxes all top-level, which allows to tick them.

**Comment by eregon** [comment]
@cadwallion I think FrozenError is already done in #568.

**Comment by cadwallion** [comment]
Why yes, yes it is. And much more thoroughly than mine. Thanks for the heads up!

**Comment by eregon** [comment]
`Process.last_status as an alias of $?`, `Thread#fetch` and `KeyError` should all be mostly straightforward and afaik not yet done.

**Comment by cadwallion** [comment]
I'll start in on both `KeyError` features.

**Comment by znz** [comment]
`Pathname.glob` with `base:` and `Pathname#glob` are missing?

**Comment by eregon** [comment]
@znz I did not add the stdlib NEWS here since it seems more important to focus on language & core changes.

The standard library is almost like gems nowadays, and we can't possibly spec all gems, it's the responsibility of their maintainers to test them properly.
That said, specs for stdlib are welcome in ruby/spec.
But full coverage of stdlib seems an unrealistic goal, which `ruby/spec` was never close to, so I think it's better to focus on language & core for now.

**Comment by nilsding** [comment]
@eregon Unless I'm missing something I guess the `Regexp/Support absent operator` part is done already (was apparently part of 2.4 already): https://github.com/ruby/spec/blob/master/language/regexp/modifiers_spec.rb#L42

**Comment by Efesto** [comment]
Hello everyone, I'm working on Kernel#pp Feature #14123

**Comment by eregon** [comment]
@Efesto Right, `Kernel#pp` already has specs, I marked it as done.

**Comment by eregon** [comment]
I wrote the specs for the final missing pieces, thank you everyone!
