### ISSUE TITLE
Write specs for new Ruby 2.6 features and changes

### ISSUE THREAD

**Issue by marcandre** [ruby/spec#640]
ruby/spec already contains some specs for 2.6, but we should aim to cover all new features and important changes.
This will improve the test coverage of these features (and maybe discover a few bugs along the way), allow other Ruby implementations to implement the changes faster with more confidence and document clearly the new behavior.

The new specs should be within a version guard block:
```ruby
ruby_version_is "2.6" do
  # New specs
end
```

NOTE: https://rubyreferences.github.io/rubychanges/2.6.html gives more details for many features and changes. 

From https://github.com/ruby/ruby/blob/trunk/doc/NEWS-2.6.0

### Language changes

- [x] <code>$SAFE</code> now is a process global state and can be set to 0 again. [Feature #14250](https://bugs.ruby-lang.org/issues/14250)

- [x] Refinements take place at block passing.  [Feature #14223](https://bugs.ruby-lang.org/issues/14223)

- [x] Refinements take place at Kernel#public_send.  [Feature #15326](https://bugs.ruby-lang.org/issues/15326)

- [x] Refinements take place at Kernel#respond_to?.  [Feature #15327](https://bugs.ruby-lang.org/issues/15327)

- [x] `else` without `rescue` now causes a syntax error.  [EXPERIMENTAL] [Feature #14606](https://bugs.ruby-lang.org/issues/14606)

- [x] Constant names may start with a non-ASCII capital letter. [Feature #13770](https://bugs.ruby-lang.org/issues/13770)

- [x] Endless ranges are introduced.  You can use a Range that has no end,
  like <code>(0..)</code> (or similarly <code>(0...)</code>).  [Feature #12912](https://bugs.ruby-lang.org/issues/12912)

  The following shows typical use cases:

    ary[1..]                              # identical to ary[1..-1]
    (1...).each {|index| block }          # infinite loop from index 1
    ary.zip(1..) {|elem, index| block }   # ary.each.with_index(1) { }

- [x] Non-Symbol keys in a keyword arguments hash always cause an exception [Feature #15138](https://bugs.ruby-lang.org/issues/15138).

- [x] The "shadowing outer local variable" warning is removed.  [Feature #12490](https://bugs.ruby-lang.org/issues/12490)

  You can now write the following without warning:
  ```ruby
  user = users.find {|user| cond(user) }
  ```

- [x] Print `cause` of the exception if the exception is not caught and printed
  its backtraces and error message. [Feature #8257](https://bugs.ruby-lang.org/issues/8257)

- [x] The flip-flop syntax is deprecated. [Feature #5400](https://bugs.ruby-lang.org/issues/5400)

### Core classes updates (outstanding ones only)

[Array]

  [New methods]

- [x] Added Array#union and Array#difference instance methods.  [Feature #14097](https://bugs.ruby-lang.org/issues/14097)

  [Modified methods]

- [x] Array#to_h now accepts a block that maps elements to new key/value pairs.  [Feature #15143](https://bugs.ruby-lang.org/issues/15143)

  [Aliased methods]

- [x] Array#filter is a new alias for Array#select. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)
- [x] Array#filter! is a new alias for Array#select!. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)

[Binding]

  [New methods]

- [x] Added Binding#source_location.  [Feature #14230](https://bugs.ruby-lang.org/issues/14230)

      This method returns the source location of the binding, a 2-element
      array of <code>__FILE__</code> and <code>__LINE__</code>.
      Traditionally, the same information could be retrieved by
      <code>eval("[__FILE__, __LINE__]", binding)</code>, but we are
      planning to change this behavior so that Kernel#eval ignores
      binding's source location [Feature #4352](https://bugs.ruby-lang.org/issues/4352).  So, users should use this
      newly-introduced method instead of Kernel#eval.

[Dir]

  [New methods]

- [x] Added Dir#each_child and Dir#children instance methods. [Feature #13969](https://bugs.ruby-lang.org/issues/13969)

[Enumerable]

  [New methods]

- [x] Enumerable#chain returns an enumerator object that iterates over the
      elements of the receiver and then those of each argument
      in sequence.  [Feature #15144](https://bugs.ruby-lang.org/issues/15144)

  [Modified methods]

- [x] Enumerable#to_h now accepts a block that maps elements to new key/value pairs.  [Feature #15143](https://bugs.ruby-lang.org/issues/15143)

  [Aliased methods]

- [x] Enumerable#filter is a new alias for Enumerable#select. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)

[Enumerator::ArithmeticSequence]

- [x] This is a new class to represent a generator of an arithmetic sequence,
    that is a number sequence defined by a common difference. It can be used
    for representing what is similar to Python's slice. You can get an
    instance of this class from Numeric#step and Range#step.

[Enumerator::Chain]

- [x] This is a new class to represent a chain of enumerables that works as a
    single enumerator, generated by such methods as Enumerable#chain and
    Enumerator#+.

[Enumerator::Lazy]

  [Aliased methods]

- [x] Enumerator::Lazy#filter is a new alias for
      Enumerator::Lazy#select.  [Feature #13784](https://bugs.ruby-lang.org/issues/13784)

[Enumerator]

  [New methods]

- [x] Enumerator#+ returns an enumerator object that iterates over the
      elements of the receiver and then those of the other operand.  [Feature #15144](https://bugs.ruby-lang.org/issues/15144)

[ENV]

  [Modified methods]

- [x] ENV.to_h now accepts a block that maps names and values to new keys and values.  [Feature #15143](https://bugs.ruby-lang.org/issues/15143)

[Exception]

  [New options]

- [x] Exception#full_message takes `:highlight` and `:order`
      options. [Feature #14324](https://bugs.ruby-lang.org/issues/14324)

[Hash]

  [Modified methods]

- [x] Hash#merge, Hash#merge!, and Hash#update now accept multiple
      arguments.  [Feature #15111](https://bugs.ruby-lang.org/issues/15111)

- [x] Hash#to_h now accepts a block that maps keys and values to new keys and values.  [Feature #15143](https://bugs.ruby-lang.org/issues/15143)

  [Aliased methods]

- [x] Hash#filter is a new alias for Hash#select.  [Feature #13784](https://bugs.ruby-lang.org/issues/13784)

- [x] Hash#filter! is a new alias for Hash#select!. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)

[IO]

  [New options]

- [x] Added new mode character <code>'x'</code> to open files for exclusive
      access. [Feature #11258](https://bugs.ruby-lang.org/issues/11258)

[Kernel]

  [Aliased methods]

- [x] Kernel#then is a new alias for Kernel#yield_self. [Feature #14594](https://bugs.ruby-lang.org/issues/14594)

  [New options]

- [x] Kernel#Complex, Kernel#Float, Kernel#Integer, and
      Kernel#Rational take an `:exception` option to specify the way of
      error handling.  [Feature #12732](https://bugs.ruby-lang.org/issues/12732)

- [x] Kernel#system takes an `:exception` option to raise an exception
      on failure.  [Feature #14386](https://bugs.ruby-lang.org/issues/14386)

  [Incompatible changes]

- [x] Kernel#system and Kernel#exec do not close non-standard file descriptors
      (the default of the `:close_others` option is changed to `false`,
      but we still set the `FD_CLOEXEC` flag on descriptors we
      create).  [Misc #14907](https://bugs.ruby-lang.org/issues/14907)

[KeyError]

  [New options]

- [x] KeyError.new accepts `:receiver` and `:key` options to set receiver and
      key in Ruby code.  [Feature #14313](https://bugs.ruby-lang.org/issues/14313)

[Method]

  [New methods]

- [x] Added Method#<< and Method#>> for Proc composition.  [Feature #6284](https://bugs.ruby-lang.org/issues/6284)

[Module]

  [Modified methods]

- [x] Module#method_defined?, Module#private_method_defined?, and
      Module#protected_method_defined? now accept the second
      parameter as optional. If it is `true` (the default value), it checks
      ancestor modules/classes, or checks only the class itself. [Feature #14944](https://bugs.ruby-lang.org/issues/14944)

[NameError]

  [New options]

- [x] NameError.new accepts a `:receiver` option to set receiver in Ruby
      code.  [Feature #14313](https://bugs.ruby-lang.org/issues/14313)

[NilClass]

  [New methods]

- [x] NilClass#=~ is added for compatibility.  [Feature #15231](https://bugs.ruby-lang.org/issues/15231)

[NoMethodError]

  [New options]

- [x] NoMethodError.new accepts a `:receiver` option to set receiver in Ruby
      code.  [Feature #14313](https://bugs.ruby-lang.org/issues/14313)

[Numeric]

  [Incompatible changes]

- [x] Numeric#step now returns an instance of the Enumerator::ArithmeticSequence
      class rather than one of the Enumerator class.

[OpenStruct]

  [Modified methods]

- [x] OpenStruct#to_h now accepts a block that maps keys and values to new keys and values.  [Feature #15143](https://bugs.ruby-lang.org/issues/15143)

[Proc]

  [New methods]

- [x] Added Proc#<< and Proc#>> for Proc composition.  [Feature #6284](https://bugs.ruby-lang.org/issues/6284)

  [Incompatible changes]

- [x] Proc#call doesn't change <code>$SAFE</code> any more.  [Feature #14250](https://bugs.ruby-lang.org/issues/14250)

[Random]

  [New methods]

- [x] Added Random.bytes.  [Feature #4938](https://bugs.ruby-lang.org/issues/4938)

[Range]

  [New methods]

- [x] Added Range#% instance method.  [Feature #14697](https://bugs.ruby-lang.org/issues/14697)

  [Incompatible changes]

- [x] Range#=== now uses the `#cover?` instead of the `#include?` method. [Feature #14575](https://bugs.ruby-lang.org/issues/14575)
- [x] Range#cover? now accepts a Range object. [Feature #14473](https://bugs.ruby-lang.org/issues/14473)
- [x] Range#step now returns an instance of the Enumerator::ArithmeticSequence
      class rather than one of the Enumerator class.

[Regexp/String]

- [x] Update Unicode version from 10.0.0 to 11.0.0. [Feature #14802](https://bugs.ruby-lang.org/issues/14802)

      This includes a rewrite of the grapheme cluster (/\X/) algorithm
      and special-casing for Georgian MTAVRULI on String#downcase.

- [x] Update Emoji version from 5.0 to 11.0.0 [Feature #14802](https://bugs.ruby-lang.org/issues/14802)

[String]

- [x] String#crypt is now deprecated. [Feature #14915](https://bugs.ruby-lang.org/issues/14915)

  [New features]

- [x] String#split yields each substring to the block if given. [Feature #4780](https://bugs.ruby-lang.org/issues/4780)

[Struct]

  [Modified methods]

- [x] Struct#to_h now accepts a block that maps keys and values to new keys and values.  [Feature #15143](https://bugs.ruby-lang.org/issues/15143)(https://bugs.ruby-lang.org/issues/15143)

  [Aliased method]

- [x] Struct#filter is a new alias for Struct#select. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)(https://bugs.ruby-lang.org/issues/13784)

[Time]

  [New features]

- [x] Time.new and Time#getlocal accept a timezone object as well as
      a UTC offset string. Time#+, Time#-, and Time#succ also preserve
      the timezone.  [Feature #14850](https://bugs.ruby-lang.org/issues/14850)

[TracePoint]

  [New features]

- [x] `script_compiled` event is supported. [Feature #15287](https://bugs.ruby-lang.org/issues/15287)

  [New methods]

- [x] TracePoint#parameters [Feature #14694](https://bugs.ruby-lang.org/issues/14694)

- [x] Not spec'd, MRI-specific. TracePoint#instruction_sequence [Feature #15287](https://bugs.ruby-lang.org/issues/15287)

- [x] TracePoint#eval_script [Feature #15287](https://bugs.ruby-lang.org/issues/15287)

  [Modified methods]

- [x] TracePoint#enable accepts new keywords `target:` and `target_line:`.
      [Feature #15289](https://bugs.ruby-lang.org/issues/15289)

**Comment by iliabylich** [comment]
>  Exception#full_message takes :highlight and :order options. Feature #14324

This change was backported into 2.5.1 and we have specs for it - https://github.com/ruby/spec/blob/master/core/exception/full_message_spec.rb#L16-L36. Could someone mark it as "done" please (or specify what's missing in specs)?

**Comment by eregon** [comment]
@iliabylich Thanks, I marked it as done, as well as the methods for which you made a PR :)

**Comment by iliabylich** [comment]
We have specs for `Kernel#system` with `exception: true` - https://github.com/ruby/spec/blob/master/core/kernel/system_spec.rb#L28-L36

**Comment by eregon** [comment]
@iliabylich  Thanks, checked.

**Comment by eregon** [comment]
Awesome progress here, I've never seen specs coming so fast :)
A huge thank you to @marcandre, @andrykonchin and @iliabylich!

Let's finish the few remaining points on the checklist :)

**Comment by iliabylich** [comment]
`String#crypt` wasn't completely deprecated - https://bugs.ruby-lang.org/projects/ruby-trunk/repository/trunk/revisions/66154/diff and I don't see event any warnings:
``` bash
$ ruby -vwe "puts 's'.crypt('salt')"
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
sa0.HzQurheWY
```

**Comment by iliabylich** [comment]
>  Added Random.bytes. Feature #4938

We have them here - https://github.com/ruby/spec/blob/master/core/random/bytes_spec.rb#L28-L32

> TracePoint#parameters Feature #14694

Same here - https://github.com/ruby/spec/blob/master/core/tracepoint/parameters_spec.rb

**Comment by eregon** [comment]
@iliabylich  Indeed, it seems no warnings where added for `String#crypt`, so no behavior changed and I'll check the checkbox. https://bugs.ruby-lang.org/issues/14915#note-38

Thanks, I checked those 2 as well.

**Comment by eregon** [comment]
We made it, all items above are spec'd now!
